# Generated by Django 2.0.5 on 2018-06-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180605_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedinuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='onlineusers',
            name='isActive',
            field=models.BooleanField(verbose_name=False),
        ),
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
